DRAWGBK(1,RGB(36,38,40),RGB(24,16,51),0,1,0);
VAR1B := (100 * (EMA(EMA(C - REF(C,1),6),6))) / (EMA(EMA(ABS(C - REF(C,1)),6),6));
抄底红箭 := ((LLV(VAR1B,2) = LLV(VAR1B,7)) AND (COUNT(VAR1B < 0,2))) AND CROSS(VAR1B,MA(VAR1B,2));
量能 := IF((MA((VOL - REF(VOL,1)) / REF(VOL,1),10)) = DRAWNULL,EMA((VOL - REF(VOL,1)) / REF(VOL,1),10),MA((VOL - REF(VOL,1)) / REF(VOL,1),10));
股价 := IF(((CLOSE - MA(CLOSE,22)) / MA(CLOSE,22)) = DRAWNULL,(CLOSE - EMA(CLOSE,22)) / EMA(CLOSE,22),(CLOSE - MA(CLOSE,22)) / MA(CLOSE,22));
主力量能 := IF(((股价 * (100 + 量能)) - (MA(股价 * (100 + 量能),7))) = DRAWNULL,(股价 * (100 + 量能)) - (EMA(股价 * (100 + 量能),7)),(股价 * (100 + 量能)) - (MA(股价 * (100 + 量能),7)));
量能金叉 := CROSS(主力量能,0);
TYP := ((HIGH + LOW) + CLOSE) / 3;
CCI := (TYP - MA(TYP,14)) / (0.015 * AVEDEV(TYP,14));
CCI金叉 := CROSS(CCI,-100);
A1 := EMA(C,14);
A1X := ((A1 - REF(A1,1)) / REF(A1,1)) * 100;
出击A := IF(A1X >= 0,REF(EMA(C,14),BARSLAST(CROSS(A1X,0)) + 1),DRAWNULL);
出击A金叉 := CROSS(A1X,0);
DIFF := EMA(CLOSE,12) - EMA(CLOSE,26);
DEA := EMA(DIFF,9);
MACD金叉 := CROSS(DIFF,DEA);
MTR := EXPMEMA(MAX(MAX(HIGH - LOW,ABS(HIGH - REF(CLOSE,1))),ABS(REF(CLOSE,1) - LOW)),14);
HD := HIGH - REF(HIGH,1);
LD := REF(LOW,1) - LOW;
DMP := EXPMEMA(IF((HD > 0) AND (HD > LD),HD,0),14);
DMM := EXPMEMA(IF((LD > 0) AND (LD > HD),LD,0),14);
PDI := (DMP * 100) / MTR;
MDI := (DMM * 100) / MTR;
ADX := EXPMEMA(((ABS(MDI - PDI)) / (MDI + PDI)) * 100,6);
ADXR := EXPMEMA(ADX,6);
X1 := MAX(C,O);
X2 := MIN(C,O);
X := ((REF(C > O,2)) AND (REF(X1,2) >= HHV(X1,2))) AND (REF(X2,2) <= LLV(X2,2));
B := BARSLAST(X) + 2;
A := ((REF(X1,B) >= HHV(X1,B)) AND (REF(X2,B) <= LLV(X2,B))) AND (EVERY(V <= REF(V,1),B));
肉夹馍 := (((REF(A,1) AND (C > O)) AND (C > REF(HHV(H,B),1))) AND (V > REF(HHV(V,B),1))) AND (EVERY(MA(C,5) > MA(C,10),B + 1));
平台起飞 : IF(((LAST(((H - L) / REF(C,1)) < 0.1,5,0)) AND (VOL > (REF(VOL,1) * 2))) AND (C > (REF(C,1) * 1.05)),1,DRAWNULL),NODRAW,COLOR6060A0;
NH := 18;
LOWV := LLV(LOW,NH);
HIGHV := HHV(HIGH,NH);
MAV := MA(V,3);
横盘 := ((HIGHV - LOWV) / NH) < 0.15;
放量1 := V >= (1.8 * MAV);
今天大阳 := ((C - REF(C,1)) / REF(C,1)) >= 0.05;
启动 : IF((横盘 AND 放量1) AND 今天大阳,1,DRAWNULL),NODRAW,COLOR4080FF;
A☆ := DMA(((H + L) + (C * 2)) / 4,0.9);
B☆ := VOL / (((H - L) * 2) - (ABS(C - O)));
C☆☆ := (IF(C > O,B☆ * (H - L),IF(C < O,B☆ * ((H - O) + (C - L)),VOL / 2))) + (IF(C > O,0 - (B☆ * ((H - C) + (O - L))),IF(C < O,0 - (B☆ * (H - L)),0 - (VOL / 2))));
A☆☆ := (C☆☆ / 20) / 1.15;
攻击流量 := ((A☆☆ * 0.618) + (REF(A☆☆,1) * 0.382)) + (REF(HSL.HSL,2) * 0.168);
B☆☆ := EMA(攻击流量,3);
流量 := IF(B☆☆ > REF(B☆☆,1),1,0);
AA☆ := ((MAX(C,O) - MIN(C,O)) / MIN(C,O)) < 0.00618;
BB☆ := ((H - MAX(C,O)) / MAX(C,O)) > 0.00382;
DD☆ := ((MIN(C,O) - L) / L) > 0.00382;
EE☆ := ((ABS(BB☆ - DD☆)) / C) < 0.00618;
星☆星 := ((AA☆ AND BB☆) AND DD☆) AND EE☆;
星线选 := ((((星☆星 = 1) AND (流量 = 1)) AND (C > O)) AND ((ABS((C - MA(C,20)) / MA(C,20))) > 0.0382)) AND ((H - MAX(C,O)) <= (MIN(C,O) - L));
星线确认 : IF(((IF((REF(星线选,1) = 1) AND (C >= REF(C,1)),1,0)) AND (C > O)) AND (((C - REF(C,1)) / REF(C,1)) > 0.00618),1,DRAWNULL),NODRAW,COLORFF3399;
一阳穿三线 : IF(((((CROSS(PDI,MDI) AND CROSS(PDI,ADX)) AND CROSS(PDI,ADXR)) AND (CLOSE > OPEN)) AND ((C / REF(C,1)) > 0.5)) AND (VOL > (MA(VOL,5) * 1.5)),1,DRAWNULL),NODRAW,COLOR800080;
T31 := (REF(C,1) / REF(C,2)) >= 1.095;
T32 := (O > REF(C,1)) AND (C > O);
T33 := ((H > C) AND (O > L)) AND (L >= REF(C,1));
T34 := V > REF(V,1);
涨停螺旋 : IF(((T31 AND T32) AND T33) AND T34,1,DRAWNULL),NODRAW,COLOR002080;
RSV := ((CLOSE - LLV(LOW,9)) / (HHV(HIGH,9) - LLV(LOW,9))) * 100;
K := SMA(RSV,3,1);
D := SMA(K,3,1);
J := (3 * K) - (2 * D);
KD金叉 := CROSS(K,D);
A1B := EMA(((L + H) + (C * 2)) / 4,14);
A1XB := ((A1B - REF(A1B,1)) / REF(A1B,1)) * 100;
出击B := IF((A1XB >= 0) AND (BARSLAST(CROSS(A1XB,0)) > 0),REF((C + O) / 2,BARSLAST(CROSS(A1XB,0))),DRAWNULL);
出击B金叉 := CROSS(出击B,0);
WMTM := CLOSE - REF(CLOSE,12);
动量金叉 := CROSS(WMTM,0);
VAR1 := (CLOSE > REF(CLOSE,1)) AND (CLOSE > REF(CLOSE,2));
VAR2 := (REF(VAR1,1) AND (CLOSE <= REF(CLOSE,1))) AND (CLOSE >= REF(CLOSE,2));
VAR3 := (REF(VAR2,1) AND (CLOSE >= REF(CLOSE,1))) AND (CLOSE <= REF(CLOSE,2));
VAR4 := (REF(VAR3,1) AND (CLOSE <= REF(CLOSE,1))) AND (CLOSE >= REF(CLOSE,2));
VAR5 := (REF(VAR4,1) AND (CLOSE >= REF(CLOSE,1))) AND (CLOSE <= REF(CLOSE,2));
VAR6 := (REF(VAR5,1) AND (CLOSE <= REF(CLOSE,1))) AND (CLOSE >= REF(CLOSE,2));
VAR7 := (REF(VAR6,1) AND (CLOSE >= REF(CLOSE,1))) AND (CLOSE <= REF(CLOSE,2));
VAR8 := (REF(VAR7,1) AND (CLOSE <= REF(CLOSE,1))) AND (CLOSE >= REF(CLOSE,2));
VAR9 := (REF(VAR8,1) AND (CLOSE >= REF(CLOSE,1))) AND (CLOSE <= REF(CLOSE,2));
VARA := (REF(VAR9,1) AND (CLOSE <= REF(CLOSE,1))) AND (CLOSE >= REF(CLOSE,2));
VARB := (REF(VARA,1) AND (CLOSE >= REF(CLOSE,1))) AND (CLOSE <= REF(CLOSE,2));
VARC := (REF(VARB,1) AND (CLOSE <= REF(CLOSE,1))) AND (CLOSE >= REF(CLOSE,2));
VARD := (CLOSE < REF(CLOSE,1)) AND (CLOSE < REF(CLOSE,2));
VARE := (REF(VARD,1) AND (CLOSE >= REF(CLOSE,1))) AND (CLOSE <= REF(CLOSE,2));
VARF := (REF(VARE,1) AND (CLOSE <= REF(CLOSE,1))) AND (CLOSE >= REF(CLOSE,2));
VAR10 := (REF(VARF,1) AND (CLOSE >= REF(CLOSE,1))) AND (CLOSE <= REF(CLOSE,2));
VAR11 := (REF(VAR10,1) AND (CLOSE <= REF(CLOSE,1))) AND (CLOSE >= REF(CLOSE,2));
VAR12 := (REF(VAR11,1) AND (CLOSE >= REF(CLOSE,1))) AND (CLOSE <= REF(CLOSE,2));
VAR13 := (REF(VAR12,1) AND (CLOSE <= REF(CLOSE,1))) AND (CLOSE >= REF(CLOSE,2));
VAR14 := (REF(VAR13,1) AND (CLOSE >= REF(CLOSE,1))) AND (CLOSE <= REF(CLOSE,2));
VAR15 := (REF(VAR14,1) AND (CLOSE <= REF(CLOSE,1))) AND (CLOSE >= REF(CLOSE,2));
VAR16 := (REF(VAR15,1) AND (CLOSE >= REF(CLOSE,1))) AND (CLOSE <= REF(CLOSE,2));
VAR17 := (REF(VAR16,1) AND (CLOSE <= REF(CLOSE,1))) AND (CLOSE >= REF(CLOSE,2));
VAR18 := (REF(VAR17,1) AND (CLOSE >= REF(CLOSE,1))) AND (CLOSE <= REF(CLOSE,2));
K线金底 := (REF(((((((((((VARD OR VARE) OR VARF) OR VAR10) OR VAR11) OR VAR12) OR VAR13) OR VAR14) OR VAR15) OR VAR16) OR VAR17) OR VAR18,1)) AND VAR1;
下跌 := ((((((((((VARD OR VARE) OR VARF) OR VAR10) OR VAR11) OR VAR12) OR VAR13) OR VAR14) OR VAR15) OR VAR16) OR VAR17) OR VAR18;
K线银底 := (下跌 AND (C > O)) AND (C > REF(C,1));
金银K线 := REF(K线银底,1) AND K线金底;
HLC := REF(MA(((HIGH + LOW) + CLOSE) / 3,10),1);
HV := EMA(HHV(HIGH,10),3);
LV := EMA(LLV(LOW,10),3);
麦克支撑压力 := EMA((HLC * 2) - LV,3);
短线突击 := EMA((C + REF(C,1)) / 2,3);
PSY := ((COUNT(CLOSE > REF(CLOSE,1),12)) / 12) * 100;
PSYMA := MA(PSY,6);
预选安全区域 := (C <= 麦克支撑压力) AND (C >= 短线突击);
做空衰歇 := CROSS(ADX,MDI);
做多金叉 := CROSS(PDI,MDI);
拉升金叉 := CROSS(ADX,ADXR) AND (PDI > MDI);
初选量能金叉 := 量能金叉 AND (金银K线 OR 抄底红箭);
初选基础池 := (预选安全区域 AND (((金银K线 OR 抄底红箭) OR 动量金叉) OR (做空衰歇 OR 做多金叉))) AND ((初选量能金叉 OR CCI金叉) OR 出击A金叉);
动量金叉确认 := (动量金叉 OR (REF(动量金叉,1) AND (拉升金叉 OR 做多金叉))) OR (做多金叉 AND 做空衰歇);
出击B金叉确认 := 出击B金叉 AND ((REF(CCI金叉 OR KD金叉,1)) OR 做空衰歇);
做多金叉确认 := 做多金叉 OR (做空衰歇 AND 拉升金叉);
MACD金叉确认 := MACD金叉 AND REF(量能金叉,1);
KD金叉确认 := KD金叉 AND (REF((金银K线 OR 抄底红箭) OR 做空衰歇,1));
稳操胜券 : IF((REF(初选基础池,1) AND ((动量金叉确认 OR 出击B金叉确认) OR 启动)) AND ((做多金叉确认 OR MACD金叉确认) OR KD金叉确认),1,DRAWNULL),COLORA000FF;
追涨 : IF(((((肉夹馍 OR 平台起飞) OR 启动) OR 一阳穿三线) OR 星线确认) OR 涨停螺旋,1,DRAWNULL),COLORRED;
关注 := ((((((((金银K线 + 抄底红箭) + 量能金叉) + CCI金叉) + CROSS(出击A,0)) + CROSS(出击B,0)) + 拉升金叉) + 做多金叉) + KD金叉) + MACD金叉;
DRAWBAND(关注,RGB(51,32,64),0,RGB(255,96,96));
STICKLINE(稳操胜券,0,9.0,0.8,0),COLORLIMAGENTA;
STICKLINE(涨停螺旋,0,4.0,0.3,0),COLOR002080;
STICKLINE(星线确认,0,3.5,0.0,0),COLORFF0080;
STICKLINE(肉夹馍,0,3.0,1.3,0),COLORRED;
STICKLINE(一阳穿三线,0,2.5,1.8,0),COLORB040B0;
STICKLINE(启动,0,2.0,2.3,0),COLOR0080FF;
STICKLINE(平台起飞,0,1.5,2.8,0),COLOR6060A0;
追涨显示条件 := ((((肉夹馍 OR 平台起飞) OR 启动) OR 一阳穿三线) OR 星线确认) OR 涨停螺旋;
金K线显示条件 := ((REFX(稳操胜券 OR 追涨显示条件,1)) OR 初选基础池) OR ((CURRBARSCOUNT <= 2) AND 初选基础池);
银K线显示条件 := (REFX(K线金底 AND 金K线显示条件,1)) OR ((CURRBARSCOUNT <= 2) AND 初选基础池);
STICKLINE(K线银底 AND 银K线显示条件,0,0.5,3.5,0),COLORLIGRAY;
STICKLINE(金银K线 AND 金K线显示条件,0,1.0,3.3,0),COLOR006060;
图标显示 := ((REFX(稳操胜券,1) OR 稳操胜券) OR 追涨显示条件) OR ((CURRBARSCOUNT <= 2) AND 初选基础池);
DRAWICON(抄底红箭 AND 图标显示,0.3,1);
DRAWICON(出击A金叉 AND 图标显示,1.0,16);
DRAWICON(出击B金叉 AND 图标显示,2.0,17);
DRAWICON(CCI金叉 AND 图标显示,3.0,25);
DRAWICON(量能金叉 AND 图标显示,4.0,26);
DRAWICON(KD金叉 AND 图标显示,5.0,27);
DRAWICON(MACD金叉 AND 图标显示,6.0,34);
DRAWICON(做多金叉 AND 图标显示,7.0,13);
DRAWICON(做空衰歇 AND 图标显示,6.5,14);
DRAWICON(拉升金叉 AND 图标显示,8.0,23);
DRAWICON(动量金叉 AND 图标显示,9.5,30);
