AA:=VOL/((HIGH-LOW)*2-ABS(CLOSE-OPEN));
买量:=IF(CLOSE>OPEN,AA*(HIGH-LOW),IF(CLOSE<OPEN,AA*((HIGH-OPEN)+(CLOSE-LOW)),VOL/2)),POINTDOT,COLORMAGENTA,LINETHICK0 ;
卖量:=IF(CLOSE>OPEN,AA*((HIGH-CLOSE)+(OPEN-LOW)),IF(CLOSE<OPEN,AA*(HIGH-LOW),VOL/2)),POINTDOT,COLORGREEN,LINETHICK0;
比:买量/卖量,COLORSTICK;
