{操作问题可以联系客服 微信号:traderByAI QQ号:2097927606;}
{更多指标，请关注微信公众号免费获取:Trader_AI;}
{欢迎指标交流QQ群:75200686,备注：指标交流;}
STICKLINE(C>0,0,0,10,0),COLORGRAY;
VV:=AMOUNT/100000000;
LB:=MA(VV,1)/HHV(VV,0);
XS:=2;
OBV:=SUM(IF(C>REF(C,1),VV,IF(C<REF(C,1),-VV,0)),180);
WOBV:=EMA(OBV,3);
ROBY:=DMA(OBV,LB/XS);
SOBV:=DMA(OBV,LB/XS/XS);
YOBV:=DMA(OBV,LB/XS/XS/XS);
SSOBC:=DMA(OBV,LB/XS/XS/XS/XS);
LOBV:=DMA(OBV,LB/XS/XS/XS/XS/XS);
QROBV:((SSOBC-LOBV+(YOBV-LOBV)/2+(SOBV-LOBV)/3+(ROBY-LOBV)/4+(WOBV-LOBV)/5)/5),COLOR00CCCC;
MQR:MA(QROBV,8),COLORGRAY;
OBC:((ROBY-LOBV)/2+(SOBV-SSOBC+YOBV-LOBV)/2+WOBV-SOBV)/3,COLOR7F00FF,LINETHICK2;
MOBV:MA(OBC,4),COLORCYAN;
IF(OBC<MOBV,OBC,DRAWNULL),LINETHICK2;
KOBV:=2*(OBC-MOBV);
DOBV:2*(QROBV-MQR),COLORSTICK;
MACDOBV:(KOBV+DOBV)/2,COLORSTICK,COLORRED;
STICKLINE(MACDOBV>=0,0,MACDOBV,1,1),COLORRED;
STICKLINE(MACDOBV<0,0,MACDOBV,1,1),COLOR00BB00;
STICKLINE(DOBV>=0,0,DOBV,0,0),COLOR00CCCC;
STICKLINE(DOBV<0,0,DOBV,0,0),COLORCYAN;
OBVH1:=REF(MACDOBV/2,BARSLAST(MACDOBV=HHV(MACDOBV,36)));
OBVH2:REF(MACDOBV/2,BARSLAST(MACDOBV=HHV(MACDOBV,72)));
大行情:=NOT(REF(OBVH1,1)=REF(OBVH2,1)) AND OBVH1=OBVH2;
DRAWTEXT(MACDOBV>OBVH1,OBVH2*2,'*'),COLORWHITE;
DRAWTEXT(大行情,OBVH2*4,'★'),COLORRED;
QGOBV:=REF(HHV(MOBV,9),1),COLORFAABEC;
QDOBV:=REF(LLV(MOBV,9),1),COLORAAAA00;
ZJGL:=(((OBC-MOBV)/ABS(MOBV)+(QROBV-MQR)/ABS(MQR)+((OBC-QROBV)/ABS(QROBV)+(MOBV-MQR)/ABS(MQR))/2)/3)*10;
DSGL:=(((OBC-MOBV)/ABS(MOBV)+(OBC-QGOBV)/ABS(QGOBV)+(MOBV-QDOBV)/ABS(QDOBV))/3)*10;
SGL:=(ZJGL+DSGL)/2;
DRAWTEXT(CROSS(ZJGL,0)AND OBC>REF(OBC,1),QROBV*0.8,'★'),COLORYELLOW;
DRAWTEXT(CROSS(DSGL,0)AND OBC>REF(OBC,1) AND OBC>QROBV,QROBV*1.25,'★'),COLORWHITE;