{-
 - 判断当前指标是多少分钟周期
 -}
TOTAL:=IF(PERIOD=1,5,IF(PERIOD=2,15,IF(PERIOD=3,30,IF(PERIOD=4,60,IF(PERIOD=5,240,1)))));

{- 
 - 求余
 - -}
MTIME:=MOD(FROMOPEN,TOTAL);

{- 
 - 这个不太可能小于0.5啊，应该ctime都等于mtime
 -}
CTIME:=IF(MTIME<0.5,TOTAL,MTIME);

{- 
 - 这其实就是按照时间比例来预估换手率而已
 -}
预估换手率:=IF((CURRBARSCOUNT=1 AND DYNAINFO(8)>1),100*VOL/(FINANCE(7)/100)*TOTAL/CTIME,DRAWNULL),NODRAW;

STICKLINE((CURRBARSCOUNT=1 AND DYNAINFO(8)>1),预估换手率,0,-1,-1),COLOR00C0C0;

换手率:100*VOL/(FINANCE(7)/100),VOLSTICK;
