VAR3:=REF(LOW,2)=LLV(LOW,5);

VAR4:=CROSS(VAR3,0.9);

VAR9:=VAR3 AND LOW>REF(LOW,1) AND H>REF(H,1);

STICKLINE(VAR4 AND CROSS(C,MA(C,5)),LOW,0,3,0),COLORWHITE;

STICKLINE(CROSS(VAR9,0.9)AND CROSS(C,MA(C,5)),VAR4,LOW,3,0),COLORYELLOW;

DRAWTEXT(VAR4 AND CROSS(C,MA(C,5)),LOW*0.9,' 买入'),COLOR00E40E;

DRAWTEXT(CROSS(VAR9,0.9)AND CROSS(C,MA(C,5)),LOW*1,' 坚定'),COLORRED;
