{操作问题可以联系客服 微信号:traderByAI QQ号:2097927606;}
{更多指标，请关注微信公众号免费获取:Trader_AI;}
{欢迎指标交流QQ群:75200686,备注：指标交流;}
N:=IF(BARSCOUNT(C)>=10,10,BARSCOUNT(C));
STICKLINE(C>=MA(C,N),MA(C,N),REF(MA(C,N),1),5,0),COLORYELLOW;
STICKLINE(C<MA(C,N),MA(C,N),REF(MA(C,N),1),5,0),COLORBLUE;

DRAWTEXT(C>=MA(C,N) AND CURRBARSCOUNT=1 AND PERIOD=5,MA(C,N),' 黄色持股 (短线)'),COLORYELLOW;
DRAWTEXT(C<MA(C,N) AND CURRBARSCOUNT=1 AND PERIOD=5,MA(C,N),' 蓝色持币 (短线)'),COLORFF9933;

M:=IF(BARSCOUNT(C)>=45,45,BARSCOUNT(C));

STICKLINE(C>=MA(C,M),MA(C,M),REF(MA(C,M),1),5,0),COLORYELLOW;
STICKLINE(C<MA(C,M),MA(C,M),REF(MA(C,M),1),5,0),COLORBLUE;

DRAWTEXT(C>=MA(C,M) AND CURRBARSCOUNT=1 AND PERIOD=5,MA(C,M),' 黄色持股 (中线)'),COLORYELLOW;
DRAWTEXT(C<MA(C,M) AND CURRBARSCOUNT=1 AND PERIOD=5,MA(C,M),' 蓝色持币 (中线)'),COLORFF9933;

DRAWKLINE(H,O,L,C);

MA5:MA(C,5),COLORMAGENTA;
MA10:MA(C,N),COLORLIRED;
MA25:MA(C,25),LINETHICK2,COLORRED;
MA45:MA(C,M),COLORGREEN;
MA120:MA(C,120),COLORBROWN;
