{- 用到未来数据 -}
MA20:MA(C,20),ColorFF8888;

三日不破:=MIN(MIN(L,REF(L,1)),REF(L,2))>=REF(L,3);
三日量缩:=(MAX(MAX(V,REF(V,1)),REF(V,2))<REF(V,3));
三日价涨A:=C>=REF(C,1);
三日价涨B:=C<REF(C,1);
三日价涨C:=MIN(MIN(C,REF(C,1)),REF(C,2))>=REF(L,3);
缩倍柱:=(VOL*1.95<=REF(VOL,1));
百日低量:=(VOL=LLV(VOL,100));
倍量柱:=C>REF(C,1)*1.04 AND (VOL>=1.9*REF(VOL,1));
四日前倍量柱:=(REF(VOL,3)>1.9*REF(VOL,4));
四日前高量柱:=(REF(VOL,3)>=REF(VOL,4) AND REF(VOL,3)<1.9*REF(VOL,4) AND 三日量缩);

前三引用不成立:=COUNT(REF(四日前倍量柱,1) AND (REF(三日不破,1) OR REF(三日价涨C,1)),3)=0 AND COUNT(REF(四日前高量柱,1) AND (REF(三日不破,1) OR REF(三日价涨C,1)),3)=0;

倍量黄金柱:=四日前倍量柱 AND 三日量缩 AND 三日不破 AND 三日价涨A AND 前三引用不成立;
高量黄金柱:=四日前高量柱 AND 三日量缩 AND 三日不破 AND 三日价涨A AND 前三引用不成立;
黄金柱:=倍量黄金柱 OR 高量黄金柱;
次倍量黄金柱:=NOT(黄金柱) AND 四日前倍量柱 AND 三日量缩 AND 三日不破 AND 三日价涨B AND 前三引用不成立;
次高量黄金柱:=NOT(黄金柱) AND 四日前高量柱 AND 三日量缩 AND 三日不破 AND 三日价涨B AND 前三引用不成立;
次黄金柱:=次倍量黄金柱 OR 次高量黄金柱;
准倍量黄金柱:=NOT(黄金柱 OR 次黄金柱) AND 四日前倍量柱 AND ((三日量缩 AND 三日价涨C) OR (COUNT(倍量柱,3)>=1 AND 三日不破)) AND 前三引用不成立;
准高量黄金柱:=NOT(黄金柱 OR 次黄金柱) AND 四日前高量柱 AND (三日量缩 AND 三日价涨C) AND 前三引用不成立;
准黄金柱:=准倍量黄金柱 OR 准高量黄金柱;
倍量将军柱:=NOT(黄金柱 OR 次黄金柱 OR 准黄金柱) AND 四日前倍量柱 AND 三日不破 AND 三日价涨A AND 前三引用不成立;
高量将军柱:=NOT(黄金柱 OR 次黄金柱 OR 准黄金柱) AND 四日前高量柱 AND 三日不破 AND 三日价涨A AND 前三引用不成立;
将军柱:=倍量将军柱 OR 高量将军柱;
次倍量将军柱:=NOT(黄金柱 OR 次黄金柱 OR 准黄金柱 OR 将军柱) AND 四日前倍量柱 AND 三日不破 AND 三日价涨B AND 前三引用不成立;
次高量将军柱:=NOT(黄金柱 OR 次黄金柱 OR 准黄金柱 OR 将军柱) AND 四日前高量柱 AND 三日不破 AND 三日价涨B AND 前三引用不成立;
次将军柱:=次倍量将军柱 OR 次高量将军柱;
准倍量将军柱:=NOT(黄金柱 OR 次黄金柱 OR 准黄金柱 OR 将军柱 OR 次将军柱) AND 四日前倍量柱 AND 三日价涨C AND 前三引用不成立;
准高量将军柱:=NOT(黄金柱 OR 次黄金柱 OR 准黄金柱 OR 将军柱 OR 次将军柱) AND 四日前高量柱 AND 三日价涨C AND 前三引用不成立;
准将军柱:=准倍量将军柱 OR 准高量将军柱;

BACKSET100:=BACKSET(黄金柱 OR 次黄金柱 OR 准黄金柱 OR 将军柱 OR 次将军柱 OR 准将军柱,4);
FILTER100:=FILTER(BACKSET100,3);
BACKSET101:=BACKSET(黄金柱,4);
FILTER101:=FILTER(BACKSET101,3);
BACKSET102:=BACKSET(次黄金柱,4);
FILTER102:=FILTER(BACKSET102,3);
BACKSET103:=BACKSET(准黄金柱,4);
FILTER103:=FILTER(BACKSET103,3);
BACKSET104:=BACKSET(将军柱,4);
FILTER104:=FILTER(BACKSET104,3);
BACKSET105:=BACKSET(次将军柱,4);
FILTER105:=FILTER(BACKSET105,3);
BACKSET106:=BACKSET(准将军柱,4);
FILTER106:=FILTER(BACKSET106,3);
DRAWTEXT(FILTER101,LOW*0.986,'↖黄金柱'),COLOR0099FF;
STICKLINE(FILTER101,OPEN,CLOSE,6,0),COLOR0099FF;
DRAWTEXT(FILTER102,LOW*0.986,'↖次黄'),COLOR00EEFF;
STICKLINE(FILTER102,OPEN,CLOSE,6,0),COLOR00EEFF;
DRAWTEXT(FILTER103,LOW*0.986,'↖准黄'),COLOR00EE99;
STICKLINE(FILTER103,OPEN,CLOSE,6,0),COLOR00EE99;
DRAWTEXT(FILTER104,LOW*0.986,'↖将军柱'),COLORRED;
STICKLINE(FILTER104,OPEN,CLOSE,6,0),COLORRED;
DRAWTEXT(FILTER105,LOW*0.986,'↖次将'),COLOR8822FF;
STICKLINE(FILTER105,OPEN,CLOSE,6,0),COLOR8822FF;
DRAWTEXT(FILTER106,LOW*0.986,'↖准将'),COLORDD22DD;
STICKLINE(FILTER106,OPEN,CLOSE,6,0),COLORDD22DD;
K1:=SUMBARS(FILTER104,1);
STICKLINE(K1,REF(L,K1-2),REF(L,K1-2),20,0),COLOR8822FF;
STICKLINE(K1,REF(L,K1-1),REF(L,K1-1),3,0),COLORGREEN;
K2:=SUMBARS(FILTER101,1);
STICKLINE(K2,REF(L,K2-2),REF(L,K2-2),20,0),COLOR0099FF;
立桩量:=VOL=HHV(VOL,40) AND VOL>1.9*REF(VOL,1);
立桩量三日突破:=IF(BARSLAST(立桩量)=1 AND CLOSE>REF(HIGH,1),1,IF(BARSLAST(立桩量)=2 AND CLOSE>REF(HIGH,2),1,IF(BARSLAST(立桩量)=3 AND CLOSE>REF(HIGH,3),1,0)));
立桩量三日不破:=BARSLAST(立桩量)=3 AND REF(LOW,3)<=MIN(MIN(C,REF(C,1)),REF(C,2));
BACKSET300:=BACKSET(立桩量三日不破,4);
BACKSET301:=BACKSET(立桩量三日突破,4);
立桩量成立:=FILTER(BACKSET300,3) AND BACKSET301 AND 立桩量;
DRAWTEXT(立桩量成立,HIGH*1.03,'←立柱'),COLORGREEN;
