{操作问题可以联系客服 微信号:traderByAI QQ号:2097927606;}
{更多指标，请关注微信公众号免费获取:Trader_AI;}
{欢迎指标交流QQ群:75200686,备注：指标交流;}
LB:=V/REF(V,1);
TLTJ:=EVERY(LB>1,3);
TLT:=BARSLAST(TLTJ);
STICKLINE(TLT,C,O,3,30),COLORGREEN;
A:=V/REF(V,TLT)<0.2;
STICKLINE(A,C,O,0.5,30),COLORGREEN;
倍量:=VOL/REF(VOL,1)>=1.9;
STICKLINE(倍量,C,O,0.5,30),COLOR00FFFF;
B:=V AND TLTJ AND A;
STICKLINE(倍量,C,O,0.5,30),COLORMAGENTA;
上跳空:=LOW-REF(HIGH,1)>0;
下跳空:=REF(L,1)>H,REF(L,1);
STICKLINE(上跳空,OPEN,CLOSE,0.7,30),COLORLIRED;
STICKLINE(下跳空,OPEN,CLOSE,0.7,30),COLORBLUE;

TKGKG:=REFX(L>REF(H,1) AND REF(H,1),1);
TKDKD:=REFX(H<REF(L,1) AND REF(H,1),1);

STICKLINE(TKDKD,C,O,0.5,30),COLORBLUE;
STICKLINE(TKGKG,C,O,0.5,30),COLORLIRED;
